pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
       stage ('Pause') {
       steps {
         echo "Taking approval from PROD manager"
         timeout(time: 7, unit: 'DAYS') {
         input message: 'Do you want to proceed to PROD?', submitter: 'admin,manager_userid'
         }
       }
     }
    }
}
